server:
    port: 3000
  
db:
    type: 'postgres'
    port: 5432
    database: 'postgres'

jwt:
    expiresIn: 3600

redis:
    host: 'localhost'
    port: 6379
    ttl: 20
    max: 100

#this file is for unit test purpose (for test env)